### Create Appointmentappointment
POST     http://localhost:3000/api/appointment
Content-Type: application/json
Accept: application/json

{
  "patientName": "Charlie green",
    "doctorEmail": "juma@gmail.com",
  "date": "2024-11-01",
  "time": "09:00",
  "fee": 130
}






