### Create Appointmentappointment
POST            http://localhost:3000/api/appointment

Content-Type: application/json
Accept: application/json

{
  "patientName": "Alice",
  "doctorEmail": "alice.doctor@example.com",
  "date": "2024-10-28T09:00:00.000Z",
  "time": "09:00 AM",
  "fee": 150
}







