GET  http://localhost:3000/api/appointment/BobJohnson
Content-Type: application/json

{
  "patientName": "Bob Johnson",
  "doctorEmail": "dr.bob@example.com",
  "date": "2024-11-02T09:30:00Z",
  "time": "9:30 AM",
  "fee": 120.0
}